# Generated by Django 3.2.7 on 2022-02-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wellness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_quality', models.CharField(choices=[('Very Good', '5'), ('Good', '4'), ('Fair', '3'), ('Poor', '2'), ('Very Poor', '1')], max_length=20)),
                ('hydration', models.CharField(choices=[('Very Good', '5'), ('Good', '4'), ('Fair', '3'), ('Poor', '2'), ('Very Poor', '1')], max_length=20)),
                ('soreness', models.CharField(choices=[('No Soreness', '5'), ('Less', '4'), ('Mild', '3'), ('Moderate', '2'), ('Severe', '1')], max_length=20)),
                ('rpe', models.CharField(choices=[('Rest', '0'), ('Really Easy', '1'), ('Easy', '2'), ('Moderate', '3'), ('Sort of Hard', '4'), ('Hard', '5'), ('Really Hard', '6'), ('Very Hard', '7'), ('Difficult', '8'), ('Maximal', '9')], max_length=20)),
            ],
        ),
    ]
