# Generated by Django 3.2.7 on 2022-02-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0002_wellness'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyCompostion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=1, verbose_name='height in cm')),
                ('weight', models.IntegerField(default=1)),
                ('BMI', models.IntegerField(default=1)),
                ('fat_percentage', models.IntegerField(default=1)),
                ('lean_mass', models.IntegerField(default=1)),
                ('visceral_fat', models.IntegerField(default=1)),
                ('fat_free_mass', models.IntegerField(default=1)),
                ('water_contebt', models.IntegerField(default=1)),
                ('subcutaneou_fat', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_limb_flexibility_right', models.IntegerField(default=1)),
                ('upper_limb_flexibility_left', models.IntegerField(default=1)),
                ('lower_limb_flexibility', models.IntegerField(default=1)),
                ('hand_grip_strength_right', models.IntegerField(default=1)),
                ('hand_grip_strength_left', models.IntegerField(default=1)),
                ('upper_limb_power', models.IntegerField(default=1)),
                ('lower_limb_power', models.IntegerField(default=1)),
                ('agility', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='wellness',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wellness',
            name='fatigue',
            field=models.CharField(choices=[('5', 'No fatigue'), ('4', 'Less fatigue'), ('3', 'Mild fatigue'), ('2', 'Moderate fatigue'), ('1', 'Severe fatigue')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='wellness',
            name='mood',
            field=models.CharField(choices=[('5', 'Very Good'), ('4', 'Good'), ('3', 'Fair'), ('2', 'Poor'), ('1', 'Very Poor')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='wellness',
            name='hydration',
            field=models.CharField(choices=[('5', 'Very Good'), ('4', 'Good'), ('3', 'Fair'), ('2', 'Poor'), ('1', 'Very Poor')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='wellness',
            name='rpe',
            field=models.CharField(choices=[('0', 'Rest'), ('1', 'Really Easy'), ('2', 'Easy'), ('3', 'Moderate'), ('4', 'Sort of Hard'), ('5', 'Hard'), ('6', 'Really Hard'), ('7', 'Very Hard'), ('8', 'Difficult'), ('9', 'Maximal')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='wellness',
            name='sleep_quality',
            field=models.CharField(choices=[('5', 'Very Good'), ('4', 'Good'), ('3', 'Fair'), ('2', 'Poor'), ('1', 'Very Poor')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='wellness',
            name='soreness',
            field=models.CharField(choices=[('5', 'No Soreness'), ('4', 'Less'), ('3', 'Mild'), ('2', 'Moderate'), ('1', 'Severe')], default=1, max_length=1),
        ),
    ]
