# Generated by Django 3.2.7 on 2022-02-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0003_auto_20220225_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fitness',
            new_name='FitnessTest',
        ),
    ]
