# Generated by Django 3.2.7 on 2022-02-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0004_rename_fitness_fitnesstest'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='email',
            field=models.EmailField(default='swetank@cssbangalore.com', max_length=254),
        ),
    ]
