# Generated by Django 3.2.7 on 2022-02-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0005_demographic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
